version: "3.9"
services:

  nginx: 
    build: ./nginx
    restart: always
    ports: 
      - 80:80

  db:
    build: ./mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  jenkins:
    build: ./jenkins
    restart: always
    ports:
      - 8000:8080
      - 50000:50000   

