version: "3.9"
services:

  nginx: 
    build: ./nginx
    restart: always
    ports: 
      - 80:80

  db:
    build: ./mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  adminer:
    build: ./adminer
    restart: always
    ports:
      - 8080:8080    

