version: "3.9"
services:

  nginx: 
    image: radiolacattor/mynginx
    restart: always
    ports: 
      - 80:80

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    env_file:
      - db.env
  
  jenkins:
    image: jenkins:2.60.3
    restart: always
    depends_on:
      db:
        condition: service_started
    ports:
      - 8080:8080
      - 50000:50000   

