---
- name: install nginx
  hosts: home
  remote_user: root

  tasks:
  - name: install nginx if it is not
    yum:
      name: nginx
      state: installed

  - name: start nginx
    service:
      name: nginx
      state: started
      enabled: true
  
    